'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SampleAPIDbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SampleAPIDbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property JenisTransaksi() As DbSet(Of JenisTransaksi)
    Public Overridable Property Mahasiswa() As DbSet(Of Mahasiswa)
    Public Overridable Property Transaksi() As DbSet(Of Transaksi)
    Public Overridable Property ViewBalance() As DbSet(Of ViewBalance)

End Class
