'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Transaksi
    Public Property TransaksiID As Integer
    Public Property Nim As String
    Public Property IdJenis As Integer
    Public Property Debet As Decimal
    Public Property Kredit As Decimal
    Public Property CurrBalance As Decimal

    Public Overridable Property JenisTransaksi As JenisTransaksi
    Public Overridable Property Mahasiswa As Mahasiswa

End Class
